spring.application.name=lessr
spring.datasource.url=jdbc:sqlite:src/data/steam_games.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.config.import=optional:classpath:application-secrets.properties
spring.cache.type=caffeine
spring.cache.caffeine.spec=expireAfterWrite=30m,maximumSize=200